Auth, Species, Substance and AnimalDiet entities
Psychol0g1st/ZooTrekker pull request #2
Opened 2023-10-18 18:17 UTC by szelszabi

# Implementált entitások:
- AnimalDiet
- Auth
- Species
- Substance

## Mindegyik entitás tartalmazza az 5 alapműveletet(save, getById, getAll, update, delete)

2023-10-18 19:07 UTC, Psychol0g1st commented on backend/src/test/java/com/example/demo/DemoApplicationTests.java
A demokat nem szeretnéd törölni? Szerintem már nincs rá szükség.

2023-10-18 19:40 UTC, Psychol0g1st commented on backend/src/main/java/hu/unideb/inf/zootrekker/entity/AnimalDiet.java
> +    private String weekdays;
Érdemes elválasztani az atributőmokat legalább egy sorral. Nagyon összefolyik így, romlik az olvashatóság. Amugy itt lehetne egy lintert rakni.

2023-10-18 19:41 UTC, Psychol0g1st commented on backend/src/main/java/hu/unideb/inf/zootrekker/entity/AnimalDiet.java
> +    private String weekdays;
Hogy automatikusan formázza

2023-10-18 19:48 UTC, szelszabi commented on backend/src/main/java/hu/unideb/inf/zootrekker/entity/AnimalDiet.java
> +    private String weekdays;
Megtörtént, nézd a legfrissebb commitot.

2023-10-18 19:59 UTC, Psychol0g1st requested changes
Az entitásoknál tegyél egy üres sort az attribútumok között. A dekorátorok és attribútumot ne válaszd el a sorok beszúrásánál.

2023-10-18 20:33 UTC, Psychol0g1st approved these changes
Nice

2023-10-23 09:33 UTC, fefedemko2001 approved these changes

2023-10-23 13:30 UTC, merged